server:
  port: 8092

spring:
  datasource:
    url: jdbc:mysql://101.37.160.249:3306/mysql_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: mysql_user
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

