spring:
  application:
    name: Flowable-Demo
  datasource:
    url: jdbc:mysql://localhost:3306/flowable-demo-data?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: holelin..
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 10086
