spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activiti3?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&nullCatalogMeansCurrent=true
    username: root
    password: holelin..
    driver-class-name: com.mysql.cj.jdbc.Driver
  activiti:
    database-schema-update: true
    history-level: full
    db-history-used: true
  jpa:
    open-in-view: false
  rabbitmq:
    username: admin
    password: admin
    host: localhost
    port: 5672
    virtual-host: /
    listener:
      # 算法相关exchange
      algorithm:
        exchange:
            durable: true
            key: algorithm.*
            name: algorithm-exchange
            type: topic
            queue: algorithm
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10
        prefetch: 1
server:
  port: 18888

