spring:
  application:
    name: Freemarker-Demo
  datasource:
    url: jdbc:mysql://localhost:3306/freemaker-demo-data?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: holelin..
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
server:
  port: 10086